  name: Shell Commands

  on: [push]
  jobs:
    run_shell_command:
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "Hello World!"
        - name: multiline script
          run: |
            node -v
            npm -v